config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, except: [:index, :destroy, :show] do
    resources :chats, only: [:create,:index, :show]
  end
  resources :users, only: [:search]do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :chats
  has_many :users, through: :group_users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :nickname, presence: true
  has_many :group_users
  has_many :chats
  has_many :groups, through: :group_users
  accepts_nested_attributes_for :groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_group, only: [:index, :create]

  def index
    @chat = Chat.new
    @chats = @group.chats
    respond_to do |format|
      format.html
      format.json { render json: @chats }
    end
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      respond_to do |format|
        format.html { redirect_to group_chats_path }
        format.json { render json: {chat: @chat, name: @chat.user.nickname} }
      end
    else
      flash.now[:alert] = 'メッセージを入力して下さい'
      render :index
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
    @groups = current_user.groups.order('id DESC')
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :show, :update]

  def index
    @groups = current_user.groups.order('id DESC').limit(5)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'チャットグループを作成しました'
    else
      flash.now[:alert] = 'グループ名を入力してください'
      render new_group_path
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'チャットグループが更新されました'
    else
      flash.now[:alert] = '入力内容を確認してください'
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    @users = User.where('nickname LIKE ?', "%#{params[:user_name]}%")
    respond_to do |format|
      format.json { render json: @users }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_chat.html.haml
%h3 #{ chat.user.nickname }
%p.date #{ chat.created_at }
%p.message #{ chat.body }
.chat-image
  = image_tag(chat.image,class: "chat-img") if chat.image?

app/views/chats/_group.html.haml
%h2 #{ group.name }

app/views/chats/index.html.haml
= javascript_include_tag "chat.js"
%body
  %header
    .heading
  .contents
    .left-content
      .top-left-content.clearfix
        %p
          =current_user.nickname
          =link_to fa_icon("edit 2x"), new_group_path
          =link_to fa_icon("cog 2x"), edit_user_registration_path
      .bottom-left-content
        = render partial: 'group', collection: @groups

    .right-content
      .top-right-content
        .box
          %h2
            =@group.name
          %ul
            %li
              Members:
              - @group.users.each do |user|
                %li
                  = user.nickname
        .box-edit
          = link_to "Edit", edit_group_path(@group), class: "Edit"
      .middle-right-content
        = render partial: 'chat', collection: @group.chats
        .chat-space-content
      .bottom-right-content
        = form_for [@group, @chat] do |f|
          = f.text_field :body,placeholder: "type a message", class: "form"
          = f.label :image do
            #{fa_icon("image 2x")}
            = f.file_field :image,style: "display: none"
          = f.submit "SEND", class: "submit"

app/views/groups/_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = text_field_tag :name,'', placeholder: "追加したいユーザー名を入力してください",id: 'keyword', class: 'chat-group-form__input'
      %ul#user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      %ul.field-input
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "SAVE", class: "chat-group-form__action-btn", disable_with: "save"

app/views/groups/_group.html.haml
=form_for [@group] do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      =f.text_field :name, placeholder: "グループ名を入力してください", class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :チャットメンバーを追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        / (別ブランチで作成)=f.text_field :, placeholder: "追加したいユーザー名を入力してください", class: 'chat-group-form__input'
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        #chat-group-user-22.chat-group-user.clearfix
          /別ブランチで実装
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "SAVE", class: "chat-group-form__action-btn", disable_with: "save"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "form"

app/views/groups/index.html.haml
%body
  %header
    .heading
  .contents
    .left-content
      .top-left-content.clearfix
        %p
          =current_user.nickname
          =link_to fa_icon("edit 2x"), new_group_path
          =link_to fa_icon("cog 2x"), edit_user_registration_path
      .bottom-left-content
        - @groups.each do |group|
          = link_to '#{group.name}', group_chats_path(@groups)
          %p まだメッセージがありません

app/views/groups/new.html.haml
= javascript_include_tag "search_user.js"
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "form"

app/views/layouts/_flash.html.haml
#flash.flash
  - flash.each do |name, msg|
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render :partial => "layouts/flash"
    = yield